users-deploy:
	bash scripts/users-deploy.sh

logger-deploy:
	bash scripts/logger-deploy.sh

reps-deploy:
	bash recurrent-expense-period-setter-deploy.sh

authorizer-deploy:
	bash lambda-authorizer-deploy.sh

income-deploy:
	bash income-deploy.sh

expenses-deploy:
	bash expenses-deploy.sh

authenticator-deploy:
	bash authenticator-deploy.sh

