users-deploy:
	bash scripts/users-deploy.sh

logger-deploy:
	bash scripts/logger-deploy.sh

reps-deploy:
	bash recurrent-expense-period-setter-deploy.sh

authorizer-deploy:
	bash scripts/lambda-authorizer-deploy.sh

income-deploy:
	bash scripts/income-deploy.sh

expenses-deploy:
	bash scripts/expenses-deploy.sh

authenticator-deploy:
	bash scripts/authenticator-deploy.sh

